### ISSUE TITLE
About DIML/CVL datasets

### ISSUE THREAD

**Issue by puyiwen** [PJ-cs/DistanceEstimationTracking#1]
Thank you for your great work! I have a question about the DIML dataset, what is the max depth of DIML outdoor dataset? And what is the max depth of DIML indoor dataset?What kind of data preprocessing should I do for this dataset? Thank you again!

**Comment by timmh** [comment]
You can find details about the DIML dataset on the [official website](https://dimlrgbd.github.io/) and the corresponding [technical report](https://dimlrgbd.github.io/downloads/technical_report.pdf).
