### ISSUE TITLE
Error due to SPVCNN_CLASSIFICATION library

### ISSUE THREAD

**Issue by AnnaKinghorn** [PJ-cs/DistanceEstimationTracking#5]
Hi! Just trying to run the code using the example you supply. There seems to be an issue with the SPVCNN_CLASSIFICATION library, as importing the library outputs the following error:

![Screenshot 2023-05-27 at 10 50 14](https://github.com/PJ-cs/DistanceEstimationTracking/assets/118733025/2b2e0433-0f22-4286-abd5-631c8ccf5381)

Also, there seems to be an issue relating to versions, as we get the following error when installing torch, torchvision and torchaudio, but is resolved by removing version numbers and "+cu111" from the code:

![Screenshot 2023-05-27 at 10 29 24](https://github.com/PJ-cs/DistanceEstimationTracking/assets/118733025/6186303e-7a00-44f0-b014-34534e6ae878)

Cheers!

**Comment by timmh** [comment]
Thanks for the detailed report! Should be fixed now, if not feel free to re-open.
